### PR TITLE
Use Apollo Router v1

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by ksvital** [comment]
Hi @kamilkisiela, looks like the publish to docker step keeps timing out close to completion, would be great if you could get the docker image published so that we could tryout router v1 with graphql-hive. Thanks 🙏

**Comment by kamilkisiela** [comment]
Yeah, that's my task for today :)

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-hive/pkgs/container/graphql-hive%2Fapollo-router

**Pull request merged**
