### PR TITLE
docs: getting started revamp

### PR DESCRIPTION
**Pull request by n1ru4l**
rewrites the page to use Tabs to provide a more streamlined and less fragmented story for the reader.

### CODE REVIEW

**Review by enisdenjo — APPROVED** [review]
Excellent!

**Review by ardatan — CHANGES_REQUESTED** [review]
https://81424ffa.hive-landing-page.pages.dev/docs/gateway/schema-registry/hive

This is kind of duplicate with this one, also it is not clear how to use it without Hive registry after removal of `Prepare Supergraph`.

Also `Next Steps` becomes confusing at the end.

**Comment by n1ru4l** [comment]
@ardatan I wanted to avoid sending one massive PR that changes everything. I am working on follow-up PRs that already address what you pointed out.

**Review by dotansimha — APPROVED** [review]

**Comment by ardatan** [comment]
> I wanted to avoid sending one massive PR that changes everything. I am working on follow-up PRs that already address what you pointed out.
Sure :) Just for the record
As I really love the idea of the tabs,
The supergraph and proxy schema source can be tabs too
Like Hive CDN, GraphOS, Custom Fetcher

**Pull request merged**
