### PR TITLE
Search list for schema page with multiple services

### PR DESCRIPTION
**Pull request by TuvalSimha**
### Background
This pull request come from #3468, the search input in schema page is bit confusing. So, we tried to make it more clear and user friendly when user have multiple services.

### Description
- Search input was changed to input with list on value changed.
- List of result should be more user friendly when have multiple services.
- Added Storybook stories.

### Before
https://github.com/kamilkisiela/graphql-hive/assets/37614975/e25cf003-1d05-4d0e-a5e9-f8a997d8d3c0

### After
https://github.com/kamilkisiela/graphql-hive/assets/37614975/b6862e06-ef9e-497a-82b5-e0e068e9eaef

### CODE REVIEW

**Comment by dotansimha** [comment]
The `Search and select schema` label seems a bit weird for me, because it makes me feel like something will happen when I select an option. 
I think it should be "filter schemas" or something like that.

**Comment by TuvalSimha** [comment]
> filter schemas

@dotansimha 
Fixed :) i changed it to `Filter schemas`

**Review by kamilkisiela — CHANGES_REQUESTED** [review]
When a user searches for a subgraph and clicks on one of the options, the schema element should not be collapsed.

Another question, how does the list look like when there are 3 subgraphs and when there are 10?

**Comment by TuvalSimha** [comment]
@kamilkisiela 
So i did rebase, fix conflicts and fixed some issues you mentioned. You can watch the video attachment and see the behaviour.

**3 schemas :**
https://github.com/kamilkisiela/graphql-hive/assets/37614975/05ba5859-b3aa-4206-8076-fe58741d4c6c

**10 schemas**
https://github.com/kamilkisiela/graphql-hive/assets/37614975/6424eb0a-6282-4984-8a09-a5355090ea73

**Review by n1ru4l — APPROVED** [review]
Approved!

Only nitpick is that "Filter schema" should probably be "Find Schema" as filter implies I can select n schemas to display?

**Review by dotansimha — APPROVED** [review]

**Comment by TuvalSimha** [comment]
> Find Schema

i will change it :) @n1ru4l

**Comment by TuvalSimha** [comment]
> Approved!
> 
> Only nitpick is that "Filter schema" should probably be "Find Schema" as filter implies I can select n schemas to display?

i will change it :) @n1ru4l

**Comment by kamilkisiela** [comment]
Let's make subgraph schemas shareable. We could move up the state of the schema picker to the url (?service=XYZ).
We can do it in a separate Pull Request.

**Comment by TuvalSimha** [comment]
> Let's make subgraph schemas shareable. We could move up the state of the schema picker to the url (?service=XYZ).
> We can do it in a separate Pull Request.

https://github.com/kamilkisiela/graphql-hive/issues/4793

**Review by kamilkisiela — APPROVED** [review]

**Pull request merged**
