### PR TITLE
feat: show clients that use a specific schema coordinate on the explorer view

### PR DESCRIPTION
**Pull request by n1ru4l**
### Background

image

Closes https://github.com/kamilkisiela/graphql-hive/issues/2050

### Description

Closes https://github.com/kamilkisiela/graphql-hive/issues/2050

### Checklist

- [ ] Input validation
- [ ] Output encoding
- [ ] Authentication management
- [ ] Session management
- [ ] Access control
- [ ] Cryptographic practices
- [ ] Error handling and logging
- [ ] Data protection
- [ ] Communication security
- [ ] System configuration
- [ ] Database security
- [ ] File management
- [ ] Memory management
- [ ] Testing

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]

**Comment by kmcgill88** [comment]
Will this PR also enable field-level visibility?

**Comment by n1ru4l** [comment]
@kmcgill88 Can you elaborate on what you mean? This PR will allow you to see what schema coordinate is used by which client.

**Comment by kmcgill88** [comment]
@n1ru4l my background is primarily in Apollo Studio so bear with me on terminology. I'm actively evaluating Hive as a replacement. In Apollo Studio terms "field insights" might be similar to what you referred to as "schema coordinate". I'm looking for which clients (and client version) are using what operations and fields in the graph. It looks like this PR does that, awesome! I just looked again in the Explorer and I'm seeing this data, I must have just overlooked it before. It threw me off that I can only see the data on mouse hover vs clicking into a details screen.

Great work here, looking forward to using it more!

**Comment by n1ru4l** [comment]
@kmcgill88 We are planning to be working on a more detailed view that will show you all operations that reference a schema coordinate. BTW schema coordinate is a term defined in https://github.com/graphql/graphql-wg/blob/main/rfcs/SchemaCoordinates.md

**Pull request merged**
