### PR TITLE
Fix router docker file

### PR DESCRIPTION
**Pull request by rcrowe**
Seems when I raised the PR with a Dockerfile I had only checked the binary ran; since then I've tried to call our graph & uncovered the following issues fixed by this PR:

- [x] Fix entrypoint was wrapped in shell, so args are not passed direct
- [x] CA bundle wasn't available so TLS requests failed
- [x] Drop `RUST_BACKTRACE`

### CODE REVIEW

**Comment by rcrowe** [comment]
@kamilkisiela @n1ru4l Any chance you could take a look at this PR? 🙏🏻 
Currently, the container is unusable

**Comment by RMHonor** [comment]
Any chance this could be looked at? @kamilkisiela @n1ru4l 

We've built this image to our own registry for now, but would be good to use an official one.

**Comment by dotansimha** [comment]
Thanks @rcrowe 
Sorry for the delay on this one, we'll try to review and get this in soon :)

**Comment by dotansimha** [comment]
@kamilkisiela I think we can close this one, since it was already fixed?

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-hive/pull/972 not merged yet

**Comment by dotansimha** [comment]
Hi @rcrowe 
Thank you for this PR, there was some more fixes needed to get this fully working, so @kamilkisiela created this PR: https://github.com/kamilkisiela/graphql-hive/pull/972 
We are looking for feedback if you are interested in giving it a try. we plan to get this merged by next week.

**Pull request closed without merging**
