### PR TITLE
Optional s3_session_token variable and remove setting region to auto

### PR DESCRIPTION
**Pull request by kamilkisiela**
#2671

### CODE REVIEW

**Comment by tapaderster** [comment]
is it good to merge?

**Comment by tapaderster** [comment]
thanks for the merge.

**Comment by kamilkisiela** [comment]
@tapaderster are you self-hosting GraphQL Hive? Maybe a shared slack channel to communicate changes, get feedback and us helping you setting it up is an option you're interested in?

**Comment by tapaderster** [comment]
Hey @kamilkisiela, yes we are. Shared Slack sounds like a good plan. We are testing it out on our end and would love to provide feedback and contribute more as we go along.

**Comment by Urigo** [comment]
@tapaderster we've sent an invite, let us know in case you haven't received it

**Pull request merged**
