### PR TITLE
fixes for hive app

### PR DESCRIPTION
**Pull request by B2o5T**
1. hide settings when don't have access to this page 

image

2. reduce animation

image

3. truncate
image

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@B2o5T rebase?

**Comment by B2o5T** [comment]
@kamilkisiela can you refactor the type error? you know what will be best approach

**Review by dotansimha — APPROVED** [review]

**Comment by n1ru4l** [comment]
@B2o5T see https://github.com/kamilkisiela/graphql-hive/pull/1483/commits/b14c2827871e23a012f39ec6d8c3935d2596f4d7

- https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#fragment-masking
- https://the-guild.dev/blog/unleash-the-power-of-fragments-with-graphql-codegen

**Review by n1ru4l — APPROVED** [review]

**Comment by B2o5T** [comment]
@n1ru4l thanks Laurin!

**Pull request merged**
