### PR TITLE
convert kafka topic & consumer group as ENV variables

### PR DESCRIPTION
**Pull request by loteresa2**
### Why
- convert Kafka topic & consumer group as ENV variables so that we can provide different value(s)

### What is changing
- Updated `usage` and `usage-ingestor` services to accept these values as ENV

### How I tested
- Tested it with https://github.com/wealthsimple/graphql-hive/pull/10
- CI test
Please let me know if I need to do any other testing.

### CODE REVIEW

**Comment by kamilkisiela** [comment]
Note to The Guild: 

> Add values of those env vars to the deployment files.

**Review by kamilkisiela — CHANGES_REQUESTED** [review]
Please also add values for those env vars in few places:
- [usage service in docker-compose.yml (integration tests)](https://github.com/kamilkisiela/graphql-hive/blob/80d029afedf585fbc69015c2071b3c24d278017c/integration-tests/docker-compose.yml#L401-L410)
- [usage-ingestor service in docker-compose.yml (integration tests)](https://github.com/kamilkisiela/graphql-hive/blob/80d029afedf585fbc69015c2071b3c24d278017c/integration-tests/docker-compose.yml#L435-L445)
- [`.env.template` in usage service](https://github.com/kamilkisiela/graphql-hive/blob/main/packages/services/usage/.env.template)
- [`.env.template` in usage-ingestor service](https://github.com/kamilkisiela/graphql-hive/blob/main/packages/services/usage-ingestor/.env.template)

**Review by n1ru4l — APPROVED** [review]

**Review by kamilkisiela — APPROVED** [review]

**Comment by n1ru4l** [comment]
@kamilkisiela Can we merge this?

**Comment by kamilkisiela** [comment]
@n1ru4l is it compatible with your docker images pr?

**Comment by n1ru4l** [comment]
@kamilkisiela yes, nothing changed there

**Pull request merged**
